### PR TITLE
Add folder with homework in master

### PR DESCRIPTION
**Pull request by Claudiu357**

### CODE REVIEW

**Review by anabmaria — CHANGES_REQUESTED** [review]
pull request declined,you delete folders from master

**Comment by Claudiu357** [comment]
> pull request declined,you delete folders from master

i deleted first from my branch and then merge intro the master folder

**Comment by anabmaria** [comment]
> > pull request declined,you delete folders from master
> 
> i deleted first from my branch and then merge intro the master folder

cand faci branch nou,el iti ia tot ce e in acel moment pe master,tu iti adaugi folderul tau sau modifici in folderul tau dar nu stergi celelalte foldere ale colegilor pentru ca atunci cand vei face merge in master le vei sterge de tot(sau adaugi la commit doar folderul tau,nu si modificarile de a sterge ce au colegii)

**Review by anabmaria — CHANGES_REQUESTED** [review]
github

Dupa cum se vede,inafara de folderul tau apare ca ai facut modificari si pe cele ale colegilor,ceea ce nu este ok.Nu se adauga manual fisierele,trebuie facut prin pull.Cel mai bine este sa reiei toti pasii inchizand acest pull request si facand un nou branch unde dupa ce ai tot ce e in master adaugi propriul fisier

**Comment by anabmaria** [comment]
github corect
un pull request corect arata asa cand vizualizezi files changed

**Pull request closed without merging**
